"""
AI Universe Multi-Agent Intelligence Client for Project FORGE.
Enables peer reasoning and debate integration with external AI Universe running at http://localhost:8000.
"""

from typing import Any

import httpx
from pydantic import BaseModel, Field

from app.core.config import Settings, get_settings
from app.core.logging import get_logger

logger = get_logger("integrations.ai_universe")


class AIUniverseResponse(BaseModel):
    """Structured response model from AI Universe reasoning API."""
    answer: str = Field(..., description="The consensus reasoning or answer from AI Universe")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Calibrated confidence score (0.0 to 1.0)")
    unresolved_disagreements: list[str] = Field(default_factory=list, description="List of lingering dissenting points or tradeoffs")
    key_evidence: list[str] = Field(default_factory=list, description="Key points of evidence supporting the consensus")
    run_id: str = Field(default="", description="Unique audit run ID generated by AI Universe")


class AIUniverseClient:
    """
    Asynchronous client for interacting with the external AI Universe multi-agent reasoning engine.
    Authenticates via the X-FRIDAY-API-Key header.
    """

    def __init__(
        self,
        base_url: str | None = None,
        api_key: str | None = None,
        timeout: float | httpx.Timeout | None = None,
    ):
        settings: Settings = get_settings()
        self.base_url = (base_url or settings.ai_universe_url).rstrip("/")
        self.api_key = api_key if api_key is not None else settings.ai_universe_api_key
        if timeout is None:
            self.timeout = httpx.Timeout(60.0, connect=5.0)
        elif isinstance(timeout, (int, float)):
            self.timeout = httpx.Timeout(timeout, connect=min(timeout, 5.0))
        else:
            self.timeout = timeout

    def _get_headers(self) -> dict[str, str]:
        """Construct request headers with API key authentication."""
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        if self.api_key:
            headers["X-FRIDAY-API-Key"] = self.api_key
        return headers

    async def ask(self, question: str, mode: str = "auto") -> AIUniverseResponse:
        """
        Query AI Universe single/auto reasoning endpoint: POST /v1/friday/ask
        """
        url = f"{self.base_url}/v1/friday/ask"
        headers = self._get_headers()
        payload = {
            "question": question,
            "mode": mode,
        }

        logger.info(f"Querying AI Universe ask endpoint: mode={mode}")
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return AIUniverseResponse(**data)

    async def generate_code(
        self,
        filename: str,
        goal: str,
        file_type: str = "python",
        requirements: list[str] | None = None,
        context: dict | None = None,
    ) -> AIUniverseResponse:
        """
        Query Inference specialized code generation service: POST /v1/forge/generate-code
        """
        url = f"{self.base_url}/v1/forge/generate-code"
        headers = self._get_headers()
        payload = {
            "filename": filename,
            "file_type": file_type,
            "requirements": requirements or [],
            "context": context or {"project_goal": goal},
        }

        logger.info(f"Querying Inference generate-code service for '{filename}'")
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return AIUniverseResponse(
                answer=data.get("code", ""),
                confidence=data.get("confidence", 0.90),
                run_id=data.get("filename", filename),
            )

    async def plan_architecture(
        self,
        goal: str,
        project_type: str = "web",
        constraints: list[str] | None = None,
        preferences: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Query Inference specialized architecture planning service: POST /v1/forge/plan-architecture
        """
        url = f"{self.base_url}/v1/forge/plan-architecture"
        headers = self._get_headers()
        payload = {
            "goal": goal,
            "project_type": project_type,
            "constraints": constraints or [],
            "preferences": preferences or [],
        }

        logger.info(f"Querying Inference architecture planning service for '{goal[:40]}'")
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            return response.json()

    async def generate_tests(
        self,
        code: str,
        file_type: str = "python",
        test_framework: str = "pytest",
        coverage_targets: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Query Inference specialized test generation service: POST /v1/forge/generate-tests
        """
        url = f"{self.base_url}/v1/forge/generate-tests"
        headers = self._get_headers()
        payload = {
            "code": code,
            "file_type": file_type,
            "test_framework": test_framework,
            "coverage_targets": coverage_targets or [],
        }

        logger.info(f"Querying Inference test generation service for {file_type} code ({len(code)} bytes)")
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            return response.json()

    async def debate(self, question: str, max_agents: int = 5) -> AIUniverseResponse:
        """
        Initiate an adversarial multi-agent debate in AI Universe for complex decisions: POST /v1/friday/debate
        """
        url = f"{self.base_url}/v1/friday/debate"
        headers = self._get_headers()
        payload = {
            "question": question,
            "max_agents": max_agents,
        }

        logger.info(f"Initiating AI Universe multi-agent debate (max_agents={max_agents})")
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return AIUniverseResponse(**data)

    async def consult_with_verification(
        self,
        question: str,
        min_confidence: float = 0.70,
        use_debate: bool = True,
        max_agents: int = 5,
    ) -> AIUniverseResponse | None:
        """
        Trust-but-verify helper:
        Consults AI Universe (via debate or ask) and evaluates the confidence score.
        If confidence >= min_confidence (default 0.70), returns the validated response.
        If confidence < min_confidence, logs a warning and returns None to trigger internal fallback.
        """
        try:
            if use_debate:
                res = await self.debate(question, max_agents=max_agents)
            else:
                res = await self.ask(question)

            if res.confidence < min_confidence:
                logger.warning(
                    f"AI Universe response confidence ({res.confidence:.2f}) is below threshold ({min_confidence:.2f}). "
                    f"Falling back to Forge internal reasoning. Disagreements: {res.unresolved_disagreements}"
                )
                return None

            logger.info(
                f"AI Universe consensus accepted with confidence {res.confidence:.2f} (run_id: {res.run_id})"
            )
            return res

        except Exception as e:
            logger.warning(f"Failed to consult AI Universe ({e}). Falling back to Forge internal reasoning.")
            return None


def get_ai_universe_client() -> AIUniverseClient:
    """Return a new instance of AIUniverseClient using current settings."""
    return AIUniverseClient()
