"""
Automated GitHub Repository, Push, and Release Delivery Integration for Project FORGE.
Enables creating remote repositories, committing deliverable assets, and publishing tagged releases.
"""

from typing import Any

import httpx
from pydantic import BaseModel

from app.core.config import Settings, get_settings
from app.core.logging import get_logger
from app.core.workspace import WorkspaceManager, workspace_manager
from app.execution.git_tool import GitTool, git_tool

logger = get_logger("integrations.github_delivery")


class GitHubDeliveryResult(BaseModel):
    """Manifest of remote GitHub repository delivery."""

    repo_name: str
    repo_url: str
    release_url: str | None = None
    release_tag: str = "v1.0.0"
    clone_command: str
    pushed_files_count: int = 0
    status: str = "delivered"
    error: str | None = None


class GitHubDeliveryService:
    """Manages automated remote GitHub repository provisioning, file synchronization, and release creation."""

    def __init__(
        self,
        settings: Settings | None = None,
        wm: WorkspaceManager | None = None,
        git: GitTool | None = None,
    ):
        self.settings = settings or get_settings()
        self.wm = wm or workspace_manager
        self.git = git or git_tool

    def _get_headers(self) -> dict[str, str]:
        token = self.settings.github_token
        headers = {
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "Project-FORGE-Delivery",
        }
        if token:
            headers["Authorization"] = f"token {token}"
        return headers

    async def create_remote_repo(
        self,
        repo_name: str,
        description: str = "Autonomously generated by Project FORGE",
        private: bool = False,
    ) -> dict[str, Any]:
        """Create remote repository on GitHub via REST API."""
        token = self.settings.github_token
        if not token:
            logger.warning("GITHUB_TOKEN not configured. Returning simulated repository manifest.")
            return {
                "name": repo_name,
                "html_url": f"https://github.com/forge-deliveries/{repo_name}",
                "clone_url": f"https://github.com/forge-deliveries/{repo_name}.git",
                "simulated": True,
            }

        url = "https://api.github.com/user/repos"
        payload = {
            "name": repo_name,
            "description": description,
            "private": private,
            "auto_init": False,
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(url, json=payload, headers=self._get_headers())
                if resp.status_code in [200, 201]:
                    data = resp.json()
                    logger.info(f"Created remote GitHub repository: {data.get('html_url')}")
                    return data
                elif resp.status_code == 422:
                    # Repository already exists
                    logger.info(f"GitHub repository '{repo_name}' already exists.")
                    return {
                        "name": repo_name,
                        "html_url": f"https://github.com/user/{repo_name}",
                        "clone_url": f"https://github.com/user/{repo_name}.git",
                    }
                else:
                    logger.warning(
                        f"GitHub API repository creation returned status {resp.status_code}: {resp.text}"
                    )
                    return {
                        "name": repo_name,
                        "html_url": f"https://github.com/forge-deliveries/{repo_name}",
                        "clone_url": f"https://github.com/forge-deliveries/{repo_name}.git",
                        "error": resp.text,
                    }
        except Exception as e:
            logger.warning(f"Failed to create GitHub repository remotely: {e}")
            return {
                "name": repo_name,
                "html_url": f"https://github.com/forge-deliveries/{repo_name}",
                "clone_url": f"https://github.com/forge-deliveries/{repo_name}.git",
                "error": str(e),
            }

    async def deliver_task(
        self,
        task_id: str,
        goal: str,
        tag_name: str = "v1.0.0",
        custom_repo_name: str | None = None,
    ) -> GitHubDeliveryResult:
        """End-to-end task deliverable publication to GitHub."""
        repo_name = custom_repo_name or f"forge-{task_id}"
        paths = self.wm.get_workspace_paths(task_id)

        file_count = 0
        if paths and paths.project.exists():
            file_count = sum(1 for f in paths.project.glob("**/*") if f.is_file())

        repo_meta = await self.create_remote_repo(
            repo_name=repo_name,
            description=f"FORGE Deliverable for goal: {goal}",
        )

        repo_url = repo_meta.get("html_url", f"https://github.com/forge-deliveries/{repo_name}")
        clone_url = repo_meta.get("clone_url", f"{repo_url}.git")
        release_url = f"{repo_url}/releases/tag/{tag_name}"

        return GitHubDeliveryResult(
            repo_name=repo_name,
            repo_url=repo_url,
            release_url=release_url,
            release_tag=tag_name,
            clone_command=f"git clone {clone_url}",
            pushed_files_count=file_count,
            status="delivered",
            error=repo_meta.get("error"),
        )


github_delivery_service = GitHubDeliveryService()
