"""
FORGE Standalone Command Line Interface (CLI) MVP.
Provides commands: build, status, logs, pause, resume, cancel, inspect.
"""

import argparse
import asyncio
from datetime import datetime
from pathlib import Path
import sys
from typing import Optional
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TextColumn
from rich.table import Table

from app.core.config import get_settings
from app.core.logging import setup_logging
from app.core.orchestrator import OrchestratorCore, orchestrator
from app.core.workspace import workspace_manager
from app.memory.db import db_manager
from app.memory.models import TaskMode, TaskState
from app.memory.state_store import StateStore
from app.memory.task_lifecycle import TaskStateMachine
from app.recovery.engine import recovery_engine
from app.verification.engine import verification_engine

# Ensure robust Windows console encoding
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

console = Console()


async def handle_build(goal: str, requirements: list[str], max_budget: float):
    """Executes full autonomous software engineering loop."""
    console.print(Panel.fit(f"[bold cyan]FORGE Engine[/bold cyan] -- Autonomous Software Synthesis\n[bold yellow]Goal:[/bold yellow] {goal}", title="Project FORGE"))

    await db_manager.init_db()

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        console=console,
    ) as progress:
        task_p = progress.add_task("[yellow]Intaking & Analyzing Task...", total=100)

        # 1. Intake & Plan
        task, graph = await orchestrator.intake_and_plan(
            goal=goal,
            requirements=requirements,
            mode=TaskMode.AUTONOMOUS,
            max_budget=max_budget,
        )
        progress.update(task_p, advance=20, description="[cyan]8-Stage Plan Synthesized. Provisioning Workspace...")

        # 2. Synthesize Initial Project Artifacts inside sandbox
        task_id = task.id
        paths = workspace_manager.get_workspace_paths(task_id)

        # Scaffold working todo or target app files if not present
        workspace_manager.write_project_file(
            task_id,
            "main.py",
            (
                '"""Generated by FORGE Autonomous Engine."""\n'
                'import sys\n\n'
                'def main():\n'
                f'    print("Running: {goal}")\n'
                '    return 0\n\n'
                'if __name__ == "__main__":\n'
                '    sys.exit(main())\n'
            ),
        )
        workspace_manager.write_project_file(
            task_id,
            "tests/test_main.py",
            (
                'from main import main\n\n'
                'def test_main():\n'
                '    assert main() == 0\n'
            ),
        )
        workspace_manager.write_project_file(
            task_id,
            "README.md",
            f"# {goal}\n\nGenerated autonomously by Project FORGE.\n",
        )

        progress.update(task_p, advance=30, description="[blue]Executing TaskGraph & Specialist Agents...")

        # 3. Step through Task Graph execution
        task = await orchestrator.run_task(task_id, max_iterations=10)

        progress.update(task_p, advance=25, description="[magenta]Running Objective Verification Battery...")

        # 4. Objective Verification
        report = await verification_engine.verify_task(task_id)

        # 5. Debug / Recovery Loop if any verification check failed
        if not report.all_passed:
            progress.update(task_p, description="[red]Verification failed. Initiating Self-Repair & Debugger...")
            for ev in report.evidence:
                if not ev.passed:
                    recovered, msg, patch = await recovery_engine.attempt_recovery(task_id, ev)
                    if recovered:
                        console.print(f"[green][OK] Self-Repair succeeded:[/green] {msg}")
                    else:
                        console.print(f"[red][FAIL] Self-Repair warning:[/red] {msg}")

        progress.update(task_p, advance=25, description="[green]Build Complete & Checkpointed!")

    # Summary Report
    table = Table(title=f"Task Completion Report: {task_id}", show_header=True, header_style="bold green")
    table.add_column("Property", style="cyan")
    table.add_column("Value", style="white")

    table.add_row("Task ID", task.id)
    table.add_row("Goal", task.goal)
    table.add_row("State", task.state.value)
    table.add_row("Progress", f"{task.progress_percentage}%")
    table.add_row("Workspace Root", task.workspace_path)
    table.add_row("Checks Passed", f"{report.passed_checks}/{report.total_checks}")

    console.print(table)


async def handle_status(task_id: str):
    """Display task progress and state."""
    await db_manager.init_db()
    store = StateStore(db_manager)
    task = await store.get_task(task_id)

    if not task:
        console.print(f"[red]Error:[/red] Task '{task_id}' not found.")
        return

    table = Table(title=f"Status: {task_id}", show_header=True, header_style="bold cyan")
    table.add_column("Metric", style="yellow")
    table.add_column("Details", style="white")

    table.add_row("Goal", task.goal)
    table.add_row("State", task.state.value)
    table.add_row("Progress", f"{task.progress_percentage}%")
    table.add_row("Budget Used", f"${task.budget_consumed:.4f} / ${task.max_budget:.2f}")
    table.add_row("Created At", task.created_at.strftime("%Y-%m-%d %H:%M:%S UTC"))
    table.add_row("Updated At", task.updated_at.strftime("%Y-%m-%d %H:%M:%S UTC"))

    console.print(table)


async def handle_logs(task_id: str, lines_count: int = 40):
    """Display recent logs for a task."""
    paths = workspace_manager.get_workspace_paths(task_id)
    if not paths or not paths.logs.exists():
        console.print(f"[red]Error:[/red] Workspace logs for task '{task_id}' not found.")
        return

    log_files = list(paths.logs.glob("*.log"))
    if not log_files:
        console.print(f"[yellow]No log files found in {paths.logs}[/yellow]")
        return

    for lf in log_files:
        console.print(f"[bold cyan]--- {lf.name} ---[/bold cyan]")
        text = lf.read_text(encoding="utf-8", errors="replace")
        tail = "\n".join(text.splitlines()[-lines_count:])
        console.print(tail if tail.strip() else "[dim](empty)[/dim]")


async def handle_pause(task_id: str, reason: str):
    """Pause a running task."""
    await db_manager.init_db()
    store = StateStore(db_manager)
    lifecycle = TaskStateMachine(store)
    try:
        updated, cp = await lifecycle.pause(task_id=task_id, reason=reason)
        console.print(f"[green][OK] Task '{task_id}' paused successfully.[/green] Checkpoint ID: [cyan]{cp.id}[/cyan]")
    except Exception as e:
        console.print(f"[red]Error pausing task:[/red] {e}")


async def handle_resume(task_id: str, reason: str):
    """Resume a paused task."""
    await db_manager.init_db()
    store = StateStore(db_manager)
    lifecycle = TaskStateMachine(store)
    try:
        updated, cp = await lifecycle.resume(task_id=task_id, reason=reason)
        console.print(f"[green][OK] Task '{task_id}' resumed successfully.[/green] Restored from checkpoint: [cyan]{cp.id if cp else 'None'}[/cyan]")
    except Exception as e:
        console.print(f"[red]Error resuming task:[/red] {e}")


async def handle_cancel(task_id: str, reason: str):
    """Cancel a task."""
    await db_manager.init_db()
    store = StateStore(db_manager)
    lifecycle = TaskStateMachine(store)
    try:
        updated = await lifecycle.cancel(task_id=task_id, reason=reason)
        console.print(f"[yellow][!] Task '{task_id}' cancelled successfully.[/yellow]")
    except Exception as e:
        console.print(f"[red]Error cancelling task:[/red] {e}")


async def handle_inspect(task_id: str):
    """Deep inspect task state, graph nodes, checkpoints, and artifacts."""
    await db_manager.init_db()
    store = StateStore(db_manager)
    task = await store.get_task(task_id)

    if not task:
        console.print(f"[red]Error:[/red] Task '{task_id}' not found.")
        return

    graph = await store.get_latest_task_graph_for_project(task_id)
    checkpoints = await store.list_checkpoints(task_id)
    events = await store.get_audit_trail(task_id)
    artifacts = await store.list_artifacts_for_task(task_id)

    console.print(Panel(f"[bold cyan]Task ID:[/bold cyan] {task.id}\n[bold yellow]Goal:[/bold yellow] {task.goal}\n[bold magenta]State:[/bold magenta] {task.state.value} ({task.progress_percentage}%)\n[bold green]Sandbox:[/bold green] {task.workspace_path}", title="Task Inspection"))

    # Nodes Table
    if graph and graph.nodes:
        table = Table(title="Task Graph Nodes", show_header=True, header_style="bold magenta")
        table.add_column("Title", style="white")
        table.add_column("Stage", style="cyan")
        table.add_column("Agent", style="yellow")
        table.add_column("Status", style="green")

        for node in graph.nodes.values():
            table.add_row(
                node.title,
                str(node.metadata.get("stage", "Unknown")),
                str(node.assigned_agent or "developer"),
                node.status.value,
            )
        console.print(table)

    console.print(f"[cyan]Checkpoints:[/cyan] {len(checkpoints)} | [cyan]Audit Events:[/cyan] {len(events)} | [cyan]Artifacts:[/cyan] {len(artifacts)}")


def main():
    """Main CLI entry point for FORGE."""
    parser = argparse.ArgumentParser(
        prog="forge",
        description="FORGE: Autonomous Software Engineering Engine CLI",
    )
    subparsers = parser.add_subparsers(dest="command", help="Command to execute")

    # forge build
    build_parser = subparsers.add_parser("build", help="Autonomously synthesize and verify a software goal")
    build_parser.add_argument("goal", type=str, help="High-level engineering goal")
    build_parser.add_argument("--req", "-r", action="append", default=[], help="Explicit constraint or requirement")
    build_parser.add_argument("--budget", "-b", type=float, default=10.0, help="Max budget in USD")

    # forge status
    status_parser = subparsers.add_parser("status", help="Inspect task status and progress")
    status_parser.add_argument("task_id", type=str, help="Task ID")

    # forge logs
    logs_parser = subparsers.add_parser("logs", help="Display workspace terminal and agent logs")
    logs_parser.add_argument("task_id", type=str, help="Task ID")
    logs_parser.add_argument("--lines", "-n", type=int, default=40, help="Lines of logs to show")

    # forge pause
    pause_parser = subparsers.add_parser("pause", help="Pause a running task and checkpoint state")
    pause_parser.add_argument("task_id", type=str, help="Task ID")
    pause_parser.add_argument("--reason", type=str, default="User requested pause", help="Reason for pause")

    # forge resume
    resume_parser = subparsers.add_parser("resume", help="Resume a paused task from latest checkpoint")
    resume_parser.add_argument("task_id", type=str, help="Task ID")
    resume_parser.add_argument("--reason", type=str, default="User requested resume", help="Reason for resume")

    # forge cancel
    cancel_parser = subparsers.add_parser("cancel", help="Cancel task execution")
    cancel_parser.add_argument("task_id", type=str, help="Task ID")
    cancel_parser.add_argument("--reason", type=str, default="User requested cancel", help="Reason for cancel")

    # forge inspect
    inspect_parser = subparsers.add_parser("inspect", help="Deep inspection of task graph and audit trail")
    inspect_parser.add_argument("task_id", type=str, help="Task ID")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "build":
        asyncio.run(handle_build(args.goal, args.req, args.budget))
    elif args.command == "status":
        asyncio.run(handle_status(args.task_id))
    elif args.command == "logs":
        asyncio.run(handle_logs(args.task_id, args.lines))
    elif args.command == "pause":
        asyncio.run(handle_pause(args.task_id, args.reason))
    elif args.command == "resume":
        asyncio.run(handle_resume(args.task_id, args.reason))
    elif args.command == "cancel":
        asyncio.run(handle_cancel(args.task_id, args.reason))
    elif args.command == "inspect":
        asyncio.run(handle_inspect(args.task_id))


if __name__ == "__main__":
    main()
